-- MySQL Script generated by MySQL Workbench
-- mer. 30 août 2017 16:43:56 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema qodisco
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `qodisco` ;

-- -----------------------------------------------------
-- Schema qodisco2
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `qodisco` DEFAULT CHARACTER SET latin1 ;
USE `qodisco` ;

-- -----------------------------------------------------
-- Table `tb_authority`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_authority` ;

CREATE TABLE IF NOT EXISTS `tb_authority` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `tb_authority`
--

LOCK TABLES `tb_authority` WRITE;
/*!40000 ALTER TABLE `tb_authority` DISABLE KEYS */;
INSERT INTO `tb_authority` VALUES (1,'ROLE_USER');
/*!40000 ALTER TABLE `tb_authority` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `tb_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_user` ;

CREATE TABLE IF NOT EXISTS `tb_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_username` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `tb_user`
--

LOCK TABLES `tb_user` WRITE;
/*!40000 ALTER TABLE `tb_user` DISABLE KEYS */;
INSERT INTO `tb_user` VALUES (1,'admin@mail.com','Admin','$2a$10$thiJPCPBgYFdW3DAf04rD.cHkEVbODDRfAtX0hpFZH9FPT2fEGJXq','admin');
/*!40000 ALTER TABLE `tb_user` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `tb_domain`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_domain` ;

CREATE TABLE IF NOT EXISTS `tb_domain` (
  `name` VARCHAR(255) NOT NULL,
  `ontology_uri` VARCHAR(255) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`name`, `user_id`),
  KEY `fk_tb_domain_tb_user1_idx` (`user_id`),
  CONSTRAINT `fk_tb_domain_tb_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tb_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `tb_domain`
--

LOCK TABLES `tb_domain` WRITE;
/*!40000 ALTER TABLE `tb_domain` DISABLE KEYS */;
INSERT INTO `tb_domain` VALUES ('Default','http://consiste.dimap.ufrn.br/ontologies/qodisco',1);
/*!40000 ALTER TABLE `tb_domain` ENABLE KEYS */;
UNLOCK TABLES;

-- -----------------------------------------------------
-- Table `tb_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_topic` ;

CREATE TABLE IF NOT EXISTS `tb_topic` (
  `topic` VARCHAR(255) NOT NULL,
  `broker_address` VARCHAR(255) NOT NULL,
  `query` LONGTEXT NOT NULL,
  `domain_name` VARCHAR(255) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `async_filter` VARCHAR(255) NULL,
  `last_query_send_date` DOUBLE NOT NULL,
  `last_query_send_value` DOUBLE NOT NULL,
  PRIMARY KEY (`topic`),
  KEY `fk_tb_topic_tb_domain1` (`domain_name`),
  KEY `fk_tb_topic_tb_user1` (`user_id`),
  KEY `fk_tb_topic_tb_filter1` (`async_filter`),
  CONSTRAINT `fk_tb_topic_tb_domain1`
    FOREIGN KEY (`domain_name`)
    REFERENCES `tb_domain` (`name`),
  CONSTRAINT `fk_tb_topic_tb_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tb_user` (`id`),
  CONSTRAINT `fk_tb_topic_tb_filter1`
    FOREIGN KEY (`async_filter`)
    REFERENCES `tb_filter` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_filter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_filter` ;

CREATE TABLE IF NOT EXISTS `tb_filter` (
  `id` VARCHAR(255) NOT NULL,
  `filter_name` VARCHAR(255) NULL,
  `value` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_repository`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_repository` ;

CREATE TABLE IF NOT EXISTS `tb_repository` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `last_check` DATETIME NULL DEFAULT NULL,
  `time` BIGINT(20) NULL DEFAULT NULL,
  `url` VARCHAR(255) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_tb_repository_tb_user1` (`user_id`),
  CONSTRAINT `fk_tb_repository_tb_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tb_user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_operation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_operation` ;

CREATE TABLE IF NOT EXISTS `tb_operation` (
  `repository_id` INT(11) NOT NULL,
  `operations` VARCHAR(255) NULL,
  KEY `fk_tb_operation_tb_repository1` (`repository_id`),
  CONSTRAINT `fk_tb_operation_tb_repository1`
    FOREIGN KEY (`repository_id`)
    REFERENCES `tb_repository` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_repository_domains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_repository_domains` ;

CREATE TABLE IF NOT EXISTS `tb_repository_domains` (
  `repository_entity_id` INT(11) NOT NULL,
  `domains_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`repository_entity_id`, `domains_name`),
  KEY `fk_tb_repository_domains_tb_domain1` (`domains_name`),
  KEY `fk_tb_repository_domains_tb_repository1` (`repository_entity_id`),
  CONSTRAINT `fk_tb_repository_domains_tb_repository1`
    FOREIGN KEY (`repository_entity_id`)
    REFERENCES `tb_repository` (`id`),
  CONSTRAINT `fk_tb_repository_domains_tb_domain1`
    FOREIGN KEY (`domains_name`)
    REFERENCES `tb_domain` (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `tb_user_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_user_permissions` ;

CREATE TABLE IF NOT EXISTS `tb_user_permissions` (
  `user_entity_id` INT(11) NOT NULL,
  `permissions_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_entity_id`, `permissions_id`),
  KEY `fk_tb_user_permissions_tb_authority1` (`permissions_id`),
  CONSTRAINT `fk_tb_user_permissions_tb_user1`
    FOREIGN KEY (`user_entity_id`)
    REFERENCES `tb_user` (`id`),
  CONSTRAINT `fk_tb_user_permissions_tb_authority1`
    FOREIGN KEY (`permissions_id`)
    REFERENCES `tb_authority` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

--
-- Dumping data for table `tb_user_permissions`
--

LOCK TABLES `tb_user_permissions` WRITE;
/*!40000 ALTER TABLE `tb_user_permissions` DISABLE KEYS */;
INSERT INTO `tb_user_permissions` VALUES (1,1);
/*!40000 ALTER TABLE `tb_user_permissions` ENABLE KEYS */;
UNLOCK TABLES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

--
-- Creating user
--
CREATE USER `qodisco`@`localhost` IDENTIFIED BY 'qodisco' ;
GRANT ALL PRIVILEGES ON qodisco.* TO `qodisco`@`localhost`;
FLUSH PRIVILEGES;
